library(tidyverse)
library(ggplot2)
library(pheatmap)
library(vegan)
library(ape) 

load("Complete.RData")
# Complete.RData generated by script Sleep_analysis.R

print("beta")
beta <- vegdist(df_species[,2:dim(df_species)[2]], index = "bray")

print("permanova test")
permanova = adonis2(beta~ANTHRO.AGE + ANTHRO.Sex + ANTHRO.BMI + META.BATCH + META.DNA.conc.ng.ul + META.DNA.postclean.reads + META.POOP.BristolMean + META.POOP.Freq + META.POOP.COLLECTION_SEASON + psqi_norm,data=Sleep_meta, permutations = 5000, method="bray")
write_tsv(x = permanova,file = "output/permanova.tsv")

save.image("output/beta_permanova.RData")